name: word_count Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:

      # 0. Клонируем репозиторий!
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Установка зависимостей
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential devscripts fakeroot lintian debhelper

      # 2. Сборка
      - name: Build project
        run: |
          chmod +x ./cicd/build.sh
          ./cicd/build.sh

      # 3. Тесты
      - name: Run tests
        run: |
          chmod +x ./cicd/test.sh
          ./cicd/test.sh

      # 4. Упаковка
      - name: Package project
        run: |
          chmod +x ./cicd/package.sh
          ./cicd/package.sh

      # 5. Проверка deb-пакета
      - name: Deb-package check
        run: |
          lintian ./debian/*.deb || true

      # 6. Загрузка артефакта
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-build
          path: |
            ./build/
            ./debian/*.deb

      # 7. Создание релиза
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8. Прикрепление .deb файла к релизу
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ../*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
